export const area = [
    { key: "서울" },
    { key: "부산" },
    { key: "인천" },
    { key: "대구" },
    { key: "대전" },
    { key: "광주" },
    { key: "경기" },
    { key: "울산" },
    { key: "세종" },
    {  key: "강원" },
    {  key: "충북" },
    {  key: "충남" },
    {  key: "전북" },
    {  key: "전남" },
    {  key: "경북" },
    {  key: "경남" },
    {  key: "제주" },
]

export const skill = [
    { key: "Java" },
    { key: "JavaScript" },
    { key: "C" },
    { key: "C++" },
    { key: "C#" },
    { key: "Python" },
    { key: "R" },
    { key: "PHP" },
    { key: "Basic" },
    { key: "Ruby" },
    { key: "Kotlin" },
    { key: "MongoDB" },
    { key: "MySQL" },
    { key: "MSSQL" },
    { key: "React" },
    { key: "Vue" },
    { key: "Node.js" },
    { key: "Angular" },
    { key: "Express" },
    { key: "TypeScript" },
    { key: "Spring" },
    { key: "Django" },
    { key: "HTML" },
    { key: "CSS" },
    { key: "Laravel" },
    { key: "Qt" },
    { key: ".Net Framwork" },
    { key: ".Net Core" },
    { key: "ASP.Net" },
    { key: "Linux" },
    { key: "Git" },
    { key: "ES6" },
]